title: ETA
author: Jefferson Alves
email: jeffealves@gmail.com
theme: jekyll-theme-cayman

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false
